export default class District {
    id: string;
    name: string;
    nameNoSensitive: string;
    nameAddr: string;
    dateModify: Date;
    dateAdd: Date;
    dateSellFrom: Date;
    dateSellTo: Date;
    dayPostSale: string;
    dayPostSaleUnit: string;
    dayWait: string;
    dayWaitUnit: string;
    modifyBy: string;
    addBy: string;
    insuranceType: string;
    productType: string;
    feeAnnual: string;
    feePeriod: string;
    isYearlyPay: boolean;
    isSeaonPay: boolean;
    isMonthlyPay: boolean;
    isHalfYearlPay: boolean;
    ageFrom: string;
    ageFromUnit: string;
    ageTo: string;
    ageToUnit: string;
    status: string;
    configExtract: boolean;
    configBirthdayWait: string;
    configPrepaid: boolean;
    constructor() {
        this.id="";
        this.name="";
        this.nameNoSensitive="";
        this.nameAddr="";
        this.dateModify=new Date();
        this.dateAdd=new Date();
        this.dateSellFrom=new Date();
        this.dateSellTo=new Date();
        this.dayPostSale="";
        this.dayPostSaleUnit="";
        this.dayWait="";
        this.dayWaitUnit="";
        this.modifyBy="";
        this.addBy="";
        this.insuranceType="";
        this.productType="";
        this.feeAnnual="";
        this.feePeriod="";
        this.isYearlyPay=undefined;
        this.isSeaonPay=undefined;
        this.isMonthlyPay=undefined;
        this.isHalfYearlPay=undefined;
        this.ageFrom="";
        this.ageFromUnit="";
        this.ageTo="";
        this.ageToUnit="";
        this.status="";
        this.configExtract=undefined;
        this.configBirthdayWait="";
        this.configPrepaid=undefined;
    }
}